---
type: 0
jarfile: ./target/mcsrvmgr-1.0-SNAPSHOT-jar-with-dependencies.jar
java: java
servers:
  - path: servers/lobby
    type: MINIGAME
    wConfig:
      serverType: MINIGAME
      mods:
      worlds:
      additionalFiles:
        - /home/stonksic/Downloads/eula.txt
        - /home/stonksic/Downloads/start.sh
      serverJar: /home/stonksic/Downloads/spigot-1.16.5.jar
      plugins:
      serverID: servers/lobby
  - path: servers/srv01
    type: MINIGAME
  - path: servers/survival
    type: FIXED